name: Honey Tester

on:
  push:
    branches: [ "fasm" ]
  pull_request:
    branches: [ "fasm" ]

jobs:
  Test:

    runs-on: ubuntu-latest
    env:
      NAME: "pyhoney"


    steps:
    
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'
    - run: sudo mkdir "/usr/share/$NAME"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install Honey
      run: make install
    - name: Run Honey
      run: |
        ls 
        python "/usr/share/$NAME/main.py"

      
